config/routes.rb
Rails.application.routes.draw do
  resources :wish_items
  resources :wishlists
  post '/rate' => 'rater#create', :as => 'rate'
  resources :cities
  resources :countries
  resources :cart_items
  resources :carts
root 'pages#home'

get "pages/contact"
get "pages/blog"
get "pages/faq"
get "pages/about"
get "pages/zip"
  resources :subcategories
  resources :categories
  resources :product_attachments
  resources :products do
  resources :bids
  end
  devise_for :users
  resources :users, :only => [:show]

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/bid.rb
class Bid < ActiveRecord::Base
belongs_to :product
belongs_to :user
end

app/models/cart.rb
class Cart < ActiveRecord::Base
belongs_to :user
has_many:cart_items,:dependent => :destroy


   def total_price
    cart_items.to_a.sum { |item| item.total_price }
   end


end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
belongs_to :product
belongs_to :cart


  def total_price
     product.selling_price
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :subcategories
end

app/models/city.rb
class City < ActiveRecord::Base
belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
has_many :cities
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
ratyrate_rateable "speed"
  has_many :wish_items
  has_many :cart_items
  belongs_to :subcategory
  belongs_to :user
  has_many :bids
  attr_accessor :category_id
  attr_accessor :subcategory_name
  has_many :product_attachments
  accepts_nested_attributes_for :product_attachments

  validates :initial_price, numericality: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :selling_price, numericality: true
  validates :description, presence: true, length: { maximum: 90 }
  #validates :availibility, presence: true, length: { maximum: 30 }

before_destroy :ensure_not_referenced_by_any_cart_item

 private

 def ensure_not_referenced_by_any_wish_item
  if wish_items.count.zero?
   return true
  else
   errors[:base]<< "wish items present"
   return false
   end
  end


 def ensure_not_referenced_by_any_cart_item
  if cart_items.count.zero?
   return true
  else
   errors[:base]<< "cart items present"
   return false
   end
  end


  def self.search_products(params)
    products = Product.order(:name)
    products = products.where("name like ?", "%#{params[:search]}%") if !params[:search].strip.empty?
    products = products.where(subcategory_id: params[:product][:subcategory_id]) if !params[:product][:subcategory_id].strip.empty?
    products
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
belongs_to :category
has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :cart_items, :through => :cart
has_many :wish_items, :through => :wishlist
has_many :bids
has_many :products

ratyrate_rater

has_many :products_with_bids, :through => :bids, :source => :product

attr_accessor :country_id
attr_accessor :city_name
belongs_to :city
validates :email, uniqueness: true
validates :name, presence: true
validates :name, uniqueness: true

has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wish_item.rb
class WishItem < ActiveRecord::Base
belongs_to :wishlist
belongs_to :product
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
has_many :wish_items, :dependent=> :destroy
belongs_to :user
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field" %><br>
  <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category_id %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %><br>
<%= link_to 'Product', new_product_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category_id %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>